### PR TITLE
containers: fix incorrect mail setup while creating user in init-db.sh

### PR DESCRIPTION
**Pull request by rhyw**

### CODE REVIEW

**Comment by rhyw** [comment]
Now working on getting rid of the user setup by openning a shell and run commands inside.

**Comment by lzaoral** [comment]
Thank you, @rhyw!  I believe we can remove that for loop completely.  @kdudka Can you confirm that you did not use this account during development in containers?

**Comment by rhyw** [comment]
I think we still need some pre populated users for dev purposes. I removed the shell stuff and use a fixture instead:
https://github.com/openscanhub/openscanhub/pull/81

**Review by kdudka — APPROVED** [review]
Thanks!  That was obviously a typo.  The prefix should be `containers: ` (with the trailing `s`) according to https://github.com/openscanhub/openscanhub/blob/main/CONTRIBUTING.md

**Comment by lzaoral** [comment]
> I think we still need some pre populated users for dev purposes. I removed the shell stuff and use a fixture instead: https://github.com/openscanhub/openscanhub/pull/81

I've approved this PR because it fixes an obvious bug and I'll move the discussion about the user list for development to #81.

**Review by lzaoral — APPROVED** [review]

**Comment by rhyw** [comment]
commit message prefix amended.

**Pull request merged**
