### PR TITLE
hub: remove a separate model used for a single permission

### PR DESCRIPTION
**Pull request by lzaoral**
The `errata_xmlrpc_scan` user permission was moved to the more appropriate `Scan` model.

### CODE REVIEW

**Comment by lzaoral** [comment]
I've recreated the migration to resolve a conflict with another migration from #107.

**Review by kdudka — APPROVED** [review]
Works as expected.  Thanks!

**Comment by kdudka** [comment]
@lzaoral I am not able to update user permissions through web UI for a user name that contains `/`:
```
Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.
```

In this case, the user is a Kerberos service principal.  However, last week I hit a similar problem with a user named `worker/...`, which OSH/kobo automatically creates for each worker.  Any idea if we could somehow relax this check at `/osh/admin/kobo_auth/user/`?

Apparently, such users exist in OSH and anything but Django Admin is able to work with them.

**Comment by lzaoral** [comment]
> @lzaoral I am not able to update user permissions through web UI for a user name that contains `/`:
> 
> ```
> Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.
> ```
> 
> In this case, the user is a Kerberos service principal. However, last week I hit a similar problem with a user named `worker/...`, which OSH/kobo automatically creates for each worker. Any idea if we could somehow relax this check at `/osh/admin/kobo_auth/user/`?
> 
> Apparently, such users exist in OSH and anything but Django Admin is able to work with them.

This is an issue unrelated to this PR.  Moved to https://github.com/openscanhub/openscanhub/issues/185.

**Pull request merged**
