### PR TITLE
hub: add `ScanAdmin` interface tests

### PR DESCRIPTION
**Pull request by i386x**
See !387 on the old instance.

### CODE REVIEW

**Comment by kdudka** [comment]
@i386x I have rebased this merge request on the current `main` branch and squashed the fix-up commit.  Do you consider it ready to be merged?

**Comment by i386x** [comment]
@kdudka yes, it is ready

**Comment by lzaoral** [comment]
@kdudka I believe you want to rebase this PR first because there were some Ci changes recently which are not yet included in the `i386x:scan-admin-iface-tests` branch.

**Comment by lzaoral** [comment]
Off-topic:  This PR introduces a special Python module for everything test related.  I suggest to move there the current unit tests as well for consistency in a follow-up PR.

**Comment by i386x** [comment]
> Off-topic: This PR introduces a special Python module for everything test related. I suggest to move there the current unit tests as well for consistency in a follow-up PR.

In many Python projects unit test are usually placed under `tests/unit/` directory, where the directory structure layout under `unit/` reflects the directory structure layout under `src/` (e.g. if you have `src/module/foo.py` the tests will be in `tests/unit/module/test_foo.py`).

**Comment by kdudka** [comment]
@lzaoral I have rebased the pull request.

**Comment by lzaoral** [comment]
@kdudka The branch must be rebased once again to include a fix for #45.

**Comment by kdudka** [comment]
I have rebased it onto `main`.

**Comment by kdudka** [comment]
@i386x I have rebased the changes and pushed a few more commits to make the tests pass with the updated admin interface. I gave up on updating `SCANS_CHANGELIST_TABLE_ITEM_*` because the table contents is now more complex and it would require a more sophisticated approach to matching of the expected output.

**Review by kdudka — APPROVED** [review]

**Comment by i386x** [comment]
@kdudka Thanks for merging! In my new team we are focusing now on UI testing (both REST API and web UI in web browser), so I will update once I have enough experience and some spare cycles, maybe on the next Day of learning (this time tests will be not so fragile).

**Comment by kdudka** [comment]
Sounds great!  Contributions to improve test coverage are certainly welcome.

**Pull request merged**
