### PR TITLE
ci: Disable patch check in codecov

### PR DESCRIPTION
**Pull request by siteshwar**
CI should not fail if a line changed through a patch is not covered by tests.

### CODE REVIEW

**Review by jamacku — COMMENTED** [review]
I don't think this is the best solution, you will lose valuable information about the impact of your change on test coverage.

I think the better approach would be to set [threshold](https://docs.codecov.com/docs/commit-status#threshold) instead.

**Comment by kdudka** [comment]
The problem is that we are not able to capture coverage for some areas of the code because python-coverage does not work well with sub-processes: https://coverage.readthedocs.io/en/coverage-5.1/subprocess.html#measuring-sub-processes  This may lead to misleading results and artificial CI failures.

**Comment by siteshwar** [comment]
> I think the better approach would be to set [threshold](https://docs.codecov.com/docs/commit-status#threshold) instead.

It can confuse new contributors due to inconsistent CI failures (as mentioned by @kdudka), but it could be a good idea for the future.

**Review by jamacku — APPROVED** [review]
LGTM :+1:

**Review by kdudka — APPROVED** [review]

**Pull request merged**
