### PR TITLE
packaging: use snapshot versioning compatible with csutils

### PR DESCRIPTION
**Pull request by kdudka**
... for RPM packages and `setuptools_scm` for versioning of Python modules and distribution tarballs.

Resolves: https://github.com/openscanhub/openscanhub/issues/45

### CODE REVIEW

**Review by frenzymadness — COMMENTED** [review]
I like the Python part. The new shell script is kinda mysterious for me but I understand its purpose. There is only one possible confusing part - when I pull this PR and build an RPM from it, the SRPM is `osh-0.9.5.20231106.215412.g9e3f9da.snapshot_releases-1.fc38.src.rpm` but the Python sdist inside is `osh-0.9.6.dev33+g9e3f9da.tar.gz` so they both have the same commit but different versions.

**Comment by kdudka** [comment]
@frenzymadness Thanks for review!  I thought we agreed on this on the last meeting in September (sorry for the delay).  The version string that we use for RPM is optimized for DNF whereas the sdist version is compatible with PEP 440.  The latter does not allow us to use `{commit_date}.{commit_time}` in the version string.

The only way to make these two version strings identical would be to rename the distribution tarball (and the top-level directory in the distribution tarball) after it is created by `setup.py sdist`.  Would this be an improvement over status quo?

**Comment by kdudka** [comment]
> The only way to make these two version strings identical would be to rename the distribution tarball (and the top-level directory in the distribution tarball) after it is created by setup.py sdist.

I have implemented this in a fix-up commit: 2ae6d01e1d9f1b25f80ebae4d72db8067614babd

**Review by lzaoral — APPROVED** [review]
LGTM!  Thanks a lot @kdudka!  Please, also remove the `__init__.py` file from the `scrips` directory because  it is useless with these changes.

**Comment by kdudka** [comment]
@lzaoral ` __init__.py` removed in commit 7d6e8b6335e4deade8b052ba449af647620ab27d.  Thanks for review!

**Pull request merged**
