### PR TITLE
worker + hub: make handling of ErrataDiffTasks more robust 

### PR DESCRIPTION
**Pull request by lzaoral**
See commit messages for details.

### CODE REVIEW

**Review by kdudka — APPROVED** [review]
Already reviewed and approved at: https://gitlab.cee.redhat.com/covscan/covscan/-/merge_requests/373

**Comment by kdudka** [comment]
Why is codecov failing the CI?  I thought we would avoid it by merging #58.

**Comment by lzaoral** [comment]
@kdudka It depends on the output of multiple jobs.  The integration tests haven't finished yet.

**Comment by lzaoral** [comment]
Marking as draft because some changes conflict with or are obsoleted by the following `kobo` PR: https://github.com/release-engineering/kobo/pull/220

**Comment by lzaoral** [comment]
Depends on https://github.com/release-engineering/kobo/pull/220.

**Comment by lzaoral** [comment]
TODO: This needs a change in spec to force a new release with fixed worker.

**Comment by lzaoral** [comment]
Drafting because the `kobo` packages in Fedora and EPEL must be updated first.

**Comment by lzaoral** [comment]
Bodhi updates: https://bodhi.fedoraproject.org/updates/?search=kobo

**Comment by lzaoral** [comment]
The EPEL `kobo` updates will reach stable today.

**Review by kdudka — APPROVED** [review]
Looks good and passed my sanity test.  Thanks!

I spotted a typo in a commit message: `exists with a non-zero exit code` -> `exits with a non-zero exit code`

**Pull request merged**
