### PR TITLE
hub: update message topics for fedora

### PR DESCRIPTION
**Pull request by siteshwar**
... and use only `started` and `finished` topics for each task.

Related: https://github.com/openscanhub/fedora-infra/issues/3

### CODE REVIEW

**Comment by siteshwar** [comment]
@lbarcziova @majamassarini Review?

**Review by majamassarini — APPROVED** [review]
Thanks a lot!

**Review by kdudka — APPROVED** [review]
Looks good to me.  Thanks!  Just to make sure, are we using verbs instead of adjectives to denote the states on purpose?

**Comment by siteshwar** [comment]
> Looks good to me. Thanks! Just to make sure, are we using verbs instead of adjectives to denote the states on purpose?

I have just put the task state from kobo in the `status` field. Let me know if they should be written differently.

**Comment by kdudka** [comment]
The [kobo states](https://github.com/release-engineering/kobo/blob/ea882524c843ece43d2193f79eef914c094ba393/kobo/client/constants.py#L14) are named `CANCELED`, `FAILED`, and `INTERRUPTED` whereas this pull request uses `cancel`, `fail`, and `interrupt`.  It is up to you.  I am fine with both the variants...

**Comment by siteshwar** [comment]
> The [kobo states](https://github.com/release-engineering/kobo/blob/ea882524c843ece43d2193f79eef914c094ba393/kobo/client/constants.py#L14) are named `CANCELED`, `FAILED`, and `INTERRUPTED` whereas this pull request uses `cancel`, `fail`, and `interrupt`. It is up to you. I am fine with both the variants...

I would leave them as it is. Thanks!

**Pull request merged**
