### PR TITLE
hub: remove the `ScanningSession` model

### PR DESCRIPTION
**Pull request by lzaoral**
Resolves: https://issues.redhat.com/browse/OSH-298

### CODE REVIEW

**Comment by lzaoral** [comment]
> This does not work well in case we update the hub but not the worker(s):
> 
> ```python
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/kobo/worker/taskmanager.py", line 423, in run_task
>     task.run()
>   File "/usr/lib/python3.9/site-packages/osh/worker/tasks/task_errata_diff_build.py", line 34, in run
>     scanning_session_id = self.args.pop("scanning_session")
> KeyError: 'scanning_session'
> Frame run in /usr/lib/python3.9/site-packages/osh/worker/tasks/task_errata_diff_build.py at line 34
> <CODE>
>       27     foreground = False
>       28     priority = 20
>       29     weight = 1.0
>       30 
>       31     def run(self):
>       32         scan_id = self.args.pop('scan_id')
>       33         mock_config = self.args.pop("mock_config")
> -->   34         scanning_session_id = self.args.pop("scanning_session")
>       35         build = self.args.pop("build")
>       36         su_user = self.args.pop("su_user", None)
>       37 
>       38         self.hub.worker.set_scan_to_scanning(scan_id)
>       39 
>       40         # update analyzers version cache if needed
> </CODE>
> ```

Good catch!  I'm going to split this changeset into hub-only and worker-only PRs.

**Comment by lzaoral** [comment]
@kdudka This PR should remove the `ScanningSession` model as much as possible while not breaking compatibility with older workers.

**Comment by lzaoral** [comment]
Sorry!  I've messed up the previous rebase.  Hopefully, the current contents on this PR are fine now.

**Review by kdudka — APPROVED** [review]
Works as expected.  Thanks!

**Pull request merged**
