### PR TITLE
hub: Make footer configurable in base template

### PR DESCRIPTION
**Pull request by siteshwar**
Resolves: https://gitlab.cee.redhat.com/covscan/covscan/-/issues/174

### CODE REVIEW

**Comment by siteshwar** [comment]
@lzaoral The changes in this pull request work fine for index page, but we need to find a way to pass `settings.BASE_HTML_FOOTER` variable to rest of the pages that are rendered through django.

**Comment by lzaoral** [comment]
What about using a separate template for the footer?  In that case, anyone can override it how they please.

**Comment by siteshwar** [comment]
>  What about using a separate template for the footer? In that case, anyone can override it how they please.

@kdudka Do you agree with this?

**Comment by siteshwar** [comment]
> Yes, that was exactly my idea. We can include the footer in the same way as we include index-content.html in osh/hub/templates/index.html and put overrides to osh-rh-conf.


Ok, I will open a separate pull request to follow up on it.

**Pull request closed without merging**
