### PR TITLE
tests: move all unit test modules to osh/tests/

### PR DESCRIPTION
**Pull request by rhyw**
Related: https://github.com/openscanhub/openscanhub/issues/281

### CODE REVIEW

**Comment by rhyw** [comment]
### Notable module path changes:

- osh/hub/scan/tests.py=>osh/tests/hub/scan/tests.py
- osh/hub/waiving/tests.py=>osh/tests/hub/waiving/tests.py
- osh/hub/scan/test_admin.py=>osh/tests/hub/admin/test_admin.py
- osh/testing/=>osh/tests/hub/admin/
- osh/client/tests/=>osh/tests/client/

### Run these tests:

```
$ podman exec osh-hub python3 osh/hub/manage.py test
Creating test database for alias 'default'...
Found 69 test(s).
System check identified no issues (0 silenced).
```
Number of discoverd unit test cases is exactly the same with before.

### Test directory hierarchy

```
$ tree osh/tests/
osh/tests/
├── __init__.py
├── client
│   ├── __init__.py
│   ├── test_cmd_build.py
│   ├── test_cmd_diff_build.py
│   ├── test_cmd_download_results.py
│   ├── test_cmd_find_tasks.py
│   ├── test_cmd_list_analyzers.py
│   ├── test_cmd_list_mock_configs.py
│   ├── test_cmd_list_profiles.py
│   ├── test_cmd_mock_build.py
│   ├── test_cmd_task_info.py
│   └── test_cmd_version_diff_build.py
└── hub
    ├── __init__.py
    ├── admin
    │   ├── __init__.py
    │   ├── html.py
    │   ├── test_admin.py
    │   ├── testcases.py
    │   └── testdata.py
    ├── scan
    │   ├── __init__.py
    │   └── tests.py
    └── waiving
        ├── __init__.py
        ├── fixtures
        │   └── initial_test_data.json
        └── tests.py
```

### Unchanged:

1. `containers/scripts/generate_integration_test_coverage.sh`
This is the script for integration tests used by the github workflows. If preferred, we could change the directory hierarch by adding 2 separate directories(unit/integration) and move the to `osh/tests/integration/` like this:
```
$ tree -L2
.
├── __init__.py
├── integration
│   └── generate_integration_test_coverage.sh
└── unit
    ├── __init__.py
    ├── client
    └── hub
```
I consider it an overkill to bring one addional layer. Let me know your thoughts.

2. `tests/{ci.fmf,ci.sh}`
No idea where the script is being used.

**Comment by kdudka** [comment]
I believe that `tests/{ci.fmf,ci.sh}` are used in the `testing-farm:*` CI jobs.

**Comment by rhyw** [comment]
> @rhyw I like the change. I have only pushed one fix-up commit to simplify the RPM packaging. Please feel free to squash it if you agree.
> 
@kdudka squashed. Thanks for the update!

**Review by kdudka — APPROVED** [review]
Looks good.  Thanks!

**Review by siteshwar — APPROVED** [review]

**Pull request merged**
