### PR TITLE
CI: use supported Fedora packages for testing

### PR DESCRIPTION
**Pull request by kdudka**
... to eliminate the following traceback with `--config=auto`:
```
% osh-cli mock-build --profile default --config=auto --nvr units-2.22-6.fc39
Traceback (most recent call last):
  File "/usr/bin/osh-cli", line 91, in <module>
    main()
  File "/usr/bin/osh-cli", line 81, in main
    parser.run()
  File "/usr/lib/python3.12/site-packages/kobo/cli.py", line 296, in run
    cmd.run(*cmd_args, **cmd_kwargs)
  File "/usr/lib/python3.12/site-packages/osh/client/commands/cmd_build.py", line 195, in run
    handle_perm_denied(e, self.parser)
  File "/usr/lib/python3.12/site-packages/osh/client/commands/cmd_build.py", line 193, in run
    task_id = self.submit_task(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/osh/client/commands/cmd_mock_build.py", line 31, in submit_task
    return self.hub.scan.mock_build(options['mock_config'],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 1461, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/kobo/xmlrpc.py", line 477, in request
    result = transport_class.request(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/kobo/xmlrpc.py", line 391, in _single_request3
    return self.parse_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 1351, in parse_response
    return u.close()
           ^^^^^^^^^
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: ParameterError: Invalid name or id value: None>
```

### CODE REVIEW

**Comment by kdudka** [comment]
I was able to fix the original CI failure.  Unfortunately, now the OSH task triggered by CI fails with:
```
>>> 2024-12-04 11:32:49	"/usr/bin/mock" "-r" "/tmp/tmpaqihpk1u/mock.cfg" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--quiet" "--no-clean" "--calculate-build-dependencies" "/tmp/csmockpwmwsbdo/units-2.23-3.fc41.src.rpm"
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1721433600
Wrote: /builddir/build/SRPMS/units-2.23-3.fc41.src.rpm
Updating and loading repositories:
 build                                  100% |  28.4 KiB/s |   3.5 KiB |  00m00s
Repositories loaded.
Package                 Arch   Version             Repository      Size
Installing:
 bison                  x86_64 3.8.2-9.fc41        build        3.5 MiB

[...]

[30/30] Installing python3-devel-0:3.13 100% |   3.3 MiB/s |   1.8 MiB |  00m01s
Warning: skipped PGP checks for 28 packages from repository: build
Complete!
ERROR: Exception(/tmp/csmockpwmwsbdo/units-2.23-3.fc41.src.rpm) Config(f41-build-repo_latest-9463f76a-af77-4df8-ad1d-2d5994e85b5d) 0 minutes 5 seconds
ERROR: Can't get location for add-determinism.x86_64

!!! 2024-12-04 11:32:56	error: failed to install build dependencies of units-2.23-3.fc41.src.rpm
```

I am not able to reproduce the failure in a `rhel9` 1minutetip machine using the same mock config:
```
onfig_opts['basedir'] = '/var/lib/mock'
config_opts['chroot_setup_cmd'] = 'install @build'
config_opts['chroothome'] = '/builddir'
config_opts['dnf_warning'] = False
config_opts['package_manager'] = 'dnf5'
config_opts['root'] = 'f41-build-repo_latest-9463f76a-af77-4df8-ad1d-2d5994e85b5d'
config_opts['rpmbuild_networking'] = False
config_opts['rpmbuild_timeout'] = 86400
config_opts['target_arch'] = 'x86_64'
config_opts['use_bootstrap_image'] = False
config_opts['use_host_resolv'] = False
config_opts['yum.conf'] = '\n\n[main]\ncachedir=/var/cache/yum\ndebuglevel=1\nlogfile=/var/log/yum.log\nreposdir=/dev/null\nretries=20\nobsoletes=1\ngpgcheck=0\nassumeyes=1\nkeepcache=1\ninstall_weak_deps=0\nstrict=1\n\n# repos\n\n[build]\nname=build\nbaseurl=https://kojipkgs.fedoraproject.org/repos/f41-build/latest/$basearch\n'

config_opts['plugin_conf']['ccache_enable'] = False
config_opts['plugin_conf']['root_cache_enable'] = False
config_opts['plugin_conf']['yum_cache_enable'] = False

config_opts['macros']['%_host'] = 'x86_64-koji-linux-gnu'
config_opts['macros']['%_host_cpu'] = 'x86_64'
config_opts['macros']['%_rpmfilename'] = '%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm'
config_opts['macros']['%_topdir'] = '/builddir/build'
config_opts['macros']['%distribution'] = 'Koji Testing'
config_opts['macros']['%packager'] = 'Koji'
config_opts['macros']['%vendor'] = 'Koji'

config_opts['use_bootstrap_image'] = True
config_opts['releasever'] = '41'
config_opts['bootstrap_image'] = 'registry.fedoraproject.org/fedora:41'
```

@siteshwar Any idea where the `add-determinism.x86_64` nonsense comes from?

**Comment by siteshwar** [comment]
> @siteshwar Any idea where the `add-determinism.x86_64` nonsense comes from?

It looks like some customization on the virtual machines used by Testing Farm.

**Comment by kdudka** [comment]
I cannot see the failure on the `testing-farm:*` tasks, only on the `integration-tests` tasks, which run the `generate_integration_test_coverage.sh` script on a Ubuntu machine: https://github.com/openscanhub/openscanhub/blob/main/.github/workflows/integration-tests.yml

**Comment by kdudka** [comment]
`add-determinism-0.3.6-3.fc41.x86_64` is an RPM package, which is installed in both the (working and non-working) cases.  If we sort the list of all packages installed by `mock --init` alphabetically, `add-determinism-0.3.6-3.fc41.x86_64` is the first item on the list.  It is unclear to me though why the package causes a trouble in the subsequent `mock --calculate-build-dependecies` step.

**Review by siteshwar — APPROVED** [review]

**Pull request closed without merging**
