### PR TITLE
hub: merge the errata app into scan

### PR DESCRIPTION
**Pull request by lzaoral**
Resolves: #199

### CODE REVIEW

**Review by kdudka — APPROVED** [review]
Looks good.

**Comment by lzaoral** [comment]
@kdudka @siteshwar Could you please confirm, that you have applied all migrations that are removed by this PR?  While not critical, there is no point in having useless tables in the DB.

**Comment by siteshwar** [comment]
LGTM

**Comment by lzaoral** [comment]
I'm going to merge this PR as it is because the `epel-9-x86_64` finishes successfully but the status got stuck.

**Pull request merged**
