### PR TITLE
hub: restrict user list/detail page access to staff users only

### PR DESCRIPTION
**Pull request by rhyw**
Related: https://github.com/release-engineering/kobo/pull/228
Related: https://github.com/release-engineering/kobo/issues/209
Related: https://issues.redhat.com/browse/OSH-78

This PR depends on upstream pull: https://github.com/release-engineering/kobo/pull/228

### CODE REVIEW

**Review by lzaoral — APPROVED** [review]
@rhyw Thanks for the contribution!

@kdudka  I have never really used the `Users` view even when it was public so fine by me.

**Review by siteshwar — APPROVED** [review]

**Comment by rhyw** [comment]
> > @lzaoral @siteshwar Do you think it is a reasonable default?
> 
> LGTM. Everything under 'Info' link seems to be directed towards admin users, so those pages should be considered for changes too.
> 

The compliance requirement cares about the potential data breach due to **user info** being exposed, there's a ticket in the issue description in jira. Thus my understanding is unless explicitly required, only users under "info" need to be restricted.

> @siteshwar This PR is a no-op when used with older `kobo` releases. Therefore, I don't believe it is necessary to pin the `kobo` version in this case. (For example #159 is a different story because the tasks would traceback with it if executed with an incompatible `kobo` version.)

the side effect would be the config, despite added, not working as expected. but I agree that no-op changes don't have to be listed as hard dependencies.


Thanks all for your review!

**Comment by siteshwar** [comment]
@rhyw The suggestions I made are something to consider for future and are not blocking merging this pull request.

**Review by kdudka — APPROVED** [review]
@rhyw Could you please update the commit message as requested in the review?

The ability to restrict user list/detail page access is added by the kobo pull request whereas this pull request changes the default.

**Comment by rhyw** [comment]
> @rhyw Could you please update the commit message as requested in the review?
> 
> The ability to restrict user list/detail page access is added by the kobo pull request whereas this pull request changes the default.

commit message amended.

**Comment by lzaoral** [comment]
\packit rebuild

**Comment by lzaoral** [comment]
Bodhi updates: https://bodhi.fedoraproject.org/updates/?search=kobo-0.32

(These are not blocking for this particular PR.)

**Comment by rhyw** [comment]
Thanks @lzaoral for the bodhi updates.

I noticed I'm unable to merge. Anything else should I do before someone helps with the merge? Thanks

**Comment by kdudka** [comment]
@rhyw I have invited you as a collaborator.  Once you accept the invite, you should be able to merge this.

**Comment by rhyw** [comment]
Thanks!

> @rhyw I have invited you as a collaborator. Once you accept the invite, you should be able to merge this.

**Pull request merged**
