### PR TITLE
Add osh-cli unit test cases

### PR DESCRIPTION
**Pull request by rhyw**
The modules can be tested via:
```
coverage run -m unittest discover -s osh/client/tests -v
```

Latest coverage report

```
Name                                            Stmts   Miss  Cover
-------------------------------------------------------------------
osh/__init__.py                                     0      0   100%
osh/client/__init__.py                             16      4    75%
osh/client/commands/__init__.py                     0      0   100%
osh/client/commands/cmd_build.py                  121      9    93%
osh/client/commands/cmd_diff_build.py              15      0   100%
osh/client/commands/cmd_download_results.py        29      1    97%
osh/client/commands/cmd_find_tasks.py              50      0   100%
osh/client/commands/cmd_list_analyzers.py          16      0   100%
osh/client/commands/cmd_list_mock_configs.py       13      0   100%
osh/client/commands/cmd_list_profiles.py           15      0   100%
osh/client/commands/cmd_mock_build.py              10      0   100%
osh/client/commands/cmd_task_info.py               31      0   100%
osh/client/commands/cmd_version_diff_build.py      40      1    98%
osh/client/commands/common.py                      33      0   100%
osh/client/commands/shortcuts.py                   97     54    44%
osh/client/conf.py                                 36     21    42%
tests/client/test_cmd_build.py                    162      0   100%
tests/client/test_cmd_diff_build.py                39      0   100%
tests/client/test_cmd_download_results.py          58      0   100%
tests/client/test_cmd_find_tasks.py                90      0   100%
tests/client/test_cmd_list_analyzers.py            40      0   100%
tests/client/test_cmd_list_mock_configs.py         30      0   100%
tests/client/test_cmd_list_profiles.py             27      0   100%
tests/client/test_cmd_mock_build.py                21      0   100%
tests/client/test_cmd_task_info.py                 65      2    97%
tests/client/test_cmd_version_diff_build.py        76      0   100%
-------------------------------------------------------------------
TOTAL                                            1130     92    92%
```

### CODE REVIEW

**Comment by siteshwar** [comment]
RPM build is failing with:

```
error: Installed (but unpackaged) file(s) found:
   /usr/lib/python3.12/site-packages/tests/__init__.py
   /usr/lib/python3.12/site-packages/tests/__pycache__/__init__.cpython-312.opt-1.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/__init__.cpython-312.pyc

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib/python3.12/site-packages/tests/__init__.py
   /usr/lib/python3.12/site-packages/tests/__pycache__/__init__.cpython-312.opt-1.pyc
   /usr/lib/python3.12/site-packages/tests/__pycache__/__init__.cpython-312.pyc
```

Please exclude `/usr/lib/python3.12/site-packages/tests/` directory in the spec file.

**Comment by lzaoral** [comment]
@siteshwar That is a cosmetic detail.

There must a agreement where should the tests be stored in, first.  TMT tests are in `tests`, OSH hub unit tests are here:
```
$ find osh/hub -name '*test*'
osh/hub/other/test_fixtures
osh/hub/waiving/fixtures/initial_test_data.json
osh/hub/waiving/tests.py
osh/hub/scan/tests.py
```
Integration tests are in `containers/scripts/generate_integration_test_coverage.sh` and #108 introduces `osh/testing` subdirectory.

I'd say that this is rather messy and should be cleaned-up first.  However, I'm rather busy with RHEL stuff at the moment so I will not volunteer to do it myself.

**Comment by rhyw** [comment]
> Please exclude `/usr/lib/python3.12/site-packages/tests/` directory in the spec file.

@siteshwar thanks. Fixed.

> Integration tests are in `containers/scripts/generate_integration_test_coverage.sh` and #108 introduces `osh/testing` subdirectory.
> 
> I'd say that this is rather messy and should be cleaned-up first. However, I'm rather busy with RHEL stuff at the moment so I will not volunteer to do it myself.

yeah but we better track it in a separate issue. I can file a gh issue for this.

**Comment by lzaoral** [comment]
Hey, @rhyw!  Just a quick heads-up.  I have not forgotten about this PR but I'm really busy with tasks related to RHEL 10 bootstrap at the moment and I develop OSH in my spare time.  I'll try to review this and #278 by the end of this month but no promises.

**Comment by rhyw** [comment]
@lzaoral Thanks. It's fine, take your time.

I've noticed some PRs may break the tests, I'll leave it as it is for some review. Before merging, I'll rebase/update to make sure the cases are updated to survive newly merged PRs.

**Comment by siteshwar** [comment]
My knowledge of python unit tests is pretty limited, but this pull request seems to bring a significant improvement in the test coverage. We should try to merge it unless there are any major issues with it. We can always improve the code later.

**Comment by rhyw** [comment]
The recent code changes in the osh-cli module would break some of the tests and reduce the coverage ratio. I'll need to rebase and give some updates later, hopefully within this month. Marking as draft for now.

Yes we have some coverage improvements according to the ci report:
https://app.codecov.io/gh/openscanhub/openscanhub/pull/273?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=openscanhub

**Comment by lzaoral** [comment]
First things first, thank you A LOT @rhyw for creating these tests!  That's highly appreciated!

I will not review the whole PR (as announced in my upstream reviewer retirement in #295) but I have looked at one the new tests at the end of May 2024 - `test_cmd_list_mock_configs.py`.  Note that my comments below are related only to `test_cmd_list_mock_configs.py`.  I haven't nor will review other test files (so the comments below may also be hints for reviews by others, mainly @siteshwar and/or @kdudka).

I see two issues with this test:

1. Minor - The implementation seems a bit over-engineered.  Using `mock` is correct here but it should be limited only to classes/methods that cannot be executed locally without actual hub access or for patching IO (`kobo` uses the same approach).  Also, the following part is dead code:
```
            self.command.stdout = stdout
            self.command.stderr = stderr
```

2. Major - The implementation does not properly check expected behaviour.  The test only checks if the captured `stdout` contains expected values but does check if the implementation did not write anything else to `stdout`.  E.g. modified implementation that also adds `fedora-39-x86_64` to the list returned by `self.command.hub.mock_config.all()` will pass as well.

This May, I have even designed a bit different approach locally (though applied only to this particular test file due to the lack of time):

1.  Let's introduce a base test class with basic hub mocking that other `osh-cli` test classes inherit from and which implements other common functionality and tests (`osh/client/tests/__init__.py`):
```diff
diff --git a/osh/client/tests/__init__.py b/osh/client/tests/__init__.py
index e69de29b..90045ca8 100644
--- a/osh/client/tests/__init__.py
+++ b/osh/client/tests/__init__.py
@@ -0,0 +1,18 @@
+import optparse
+from kobo.client import ClientCommandContainer
+from unittest.mock import MagicMock
+
+
+class OSHCLITestBase():
+    def setup_cmd(self, PluginCls):
+        container = ClientCommandContainer(conf={})
+        name = container.register_plugin(PluginCls)
+        self.command = container[name](parser=optparse.OptionParser())
+
+        self.command.hub = MagicMock()
+        self.command.set_hub = MagicMock()
+
+    def test_options(self):
+        self.command.options()
+        self.assertEqual(self.command.parser.usage,
+                         f"%prog {self.command.normalized_name} [options] <args>")
```

2. Then, `osh/client/tests/test_cmd_list_mock_configs.py` can be simplified and improved like this (with some extra code style changes as well):
```diff
diff --git a/osh/client/tests/test_cmd_list_mock_configs.py b/osh/client/tests/test_cmd_list_mock_configs.py
index d8acf4d0..fbcdae93 100644
--- a/osh/client/tests/test_cmd_list_mock_configs.py
+++ b/osh/client/tests/test_cmd_list_mock_configs.py
@@ -1,43 +1,31 @@
 import io
-import optparse
 import unittest
-from unittest.mock import MagicMock, patch
+from unittest.mock import patch

 from osh.client.commands.cmd_list_mock_configs import List_Mock_Configs
+from osh.client.tests import OSHCLITestBase


-class TestListMockConfigs(unittest.TestCase):
+class TestListMockConfigs(OSHCLITestBase, unittest.TestCase):
     def setUp(self):
-        self.mock_option_parser = MagicMock(spec=optparse.OptionParser)
-        self.mock_hub = MagicMock()
-        self.command = List_Mock_Configs(parser=self.mock_option_parser)
-        self.command.connect_to_hub = MagicMock()
-        self.command.hub = self.mock_hub
+        self.setup_cmd(List_Mock_Configs)
+
         self.command.hub.mock_config.all.return_value = [
             {"name": "rhel-6-x86_64", "enabled": False},
             {"name": "rhel-7-x86_64", "enabled": True},
             {"name": "rhel-8-x86_64", "enabled": True},
         ]
-        # crucial attribute to avoid a RecursionError raised from kobo.client.ClientCommand
-        self.command.container = MagicMock()
-        self.command.normalized_name = "list-mock-configs"
-
-    def test_options(self):
-        self.command.options()
-        assert self.command.parser.usage == f"%prog {self.command.normalized_name} [options] <args>"

     def test_list_mock_configs(self):
-        with patch('sys.stdout', new=io.StringIO()) as stdout, \
-             patch('sys.stderr', new=io.StringIO()) as stderr:
-            self.command.stdout = stdout
-            self.command.stderr = stderr
+        with patch('sys.stdout', new=io.StringIO()) as fakeout, \
+             patch('sys.stderr', new=io.StringIO()) as fakeerr:
             self.command.run()
+
         expected_output = ["rhel-7-x86_64", "rhel-8-x86_64"]
-        actual_output = self.command.stdout.getvalue().strip()
+        actual_output = fakeout.getvalue().strip().split('\n')
+
         # All enabled mock configs should be listed
-        for line in expected_output:
-            self.assertIn(line, actual_output)
-        # Disabled mock config is not listed
-        self.assertNotIn("rhel-6-x86_64", actual_output)
-        err_output = self.command.stderr.getvalue().strip()
+        self.assertEqual(actual_output, expected_output)
+
+        err_output = fakeerr.getvalue().strip()
         self.assertEqual("NAME", err_output)

```

BTW, a7f2f37f82567c65ba7bd8af3170fae360e08ad1 is a redundant commit that fixes a problem in previous commits and just complicates git history.

**Comment by rhyw** [comment]
I'll give a careful check when got time working on it! Will reply by then. thanks for the detailed review.

**Comment by rhyw** [comment]
@lzaoral  The setup_cmd indeed makes case setUp much easier. I didn't know those kobo builtins. Lots of redundant code removed, huge thanks! The only exception is for `TestBaseBuild` where `Base_Build` is not enabled thus fails the setup_cmd, thus `TestBaseBuild.setUp` is not re-using the snippts.

I also did some clean up of history commits to make it less tedious.

Marking as review.

**Review by kdudka — APPROVED** [review]
@rhyw Looks good to me.  Thanks for the update!

Let's wait for a week or so in case @siteshwar has any comments on this.

**Comment by siteshwar** [comment]
> Let's wait for a week or so in case @siteshwar has any comments on this.

I had a quick look at it. LGTM.

**Review by siteshwar — APPROVED** [review]

**Comment by rhyw** [comment]
Thanks for all the review!

**Pull request merged**
