### PR TITLE
hub: add menu item for failed tasks

### PR DESCRIPTION
**Pull request by rhyw**
Resolves: https://github.com/openscanhub/openscanhub/issues/85
Related: https://github.com/release-engineering/kobo/pull/231
Related: https://issues.redhat.com/browse/OSH-340

### CODE REVIEW

**Comment by rhyw** [comment]
Marking as draft for now, awaiting kobo PR: https://github.com/release-engineering/kobo/pull/231

**Comment by kdudka** [comment]
Marking as ready because the needed kobo change was merged last week.

**Comment by kdudka** [comment]
As pointed out by @lzaoral and Packit, the updated kobo packages are not yet available in Fedora/EPEL.  Switching back to draft...

**Review by lzaoral — COMMENTED** [review]
The code looks good!  Thanks, @rhyw!  Don't forget to also update `README.md` with the version requirements and I apologise in advance for possible conflicts with #159.

**Comment by rhyw** [comment]
> The code looks good! Thanks, @rhyw! Don't forget to also update `README.md` with the version requirements and I apologise in advance for possible conflicts with #159.

Updated. No worries I'll rebase after it's merged.

Also I'm curious what do we do If we want the latest kobo to be available in Packit? I assume kobo verision bump would be failing the pipeline each time a new tag is needed while it's not available yet in fedora/epel.

**Comment by lzaoral** [comment]
> Also I'm curious what do we do If we want the latest kobo to be available in Packit? I assume kobo verision bump would be failing the pipeline each time a new tag is needed while it's not available yet in fedora/epel.

Correct.  Packit is just a service that schedules automated builds and tests of RPM packages in COPR and Testing Farm, respectively.  It is actually a good thing that it fails now because it prevents us from merging PRs that would end up with broken or uninstallable packages in the OSH development COPR repo which build snapshots from the `main` branch: https://copr.fedorainfracloud.org/coprs/g/openscanhub/devel/

**Comment by lzaoral** [comment]
Bodhi updates for `kobo` 0.33.0: https://bodhi.fedoraproject.org/updates/?search=kobo-0.33.0

**Comment by lzaoral** [comment]
The `kobo` update has reached stable Fedora repositories today!

/packit recheck-failed

**Comment by lzaoral** [comment]
Darn... the correct command is:

/packit retest-failed

**Review by kdudka — APPROVED** [review]
Works as expected.  Thanks!

**Comment by rhyw** [comment]
Thanks for the review/verification.

**Pull request merged**
