### PR TITLE
hub: update fixtures

### PR DESCRIPTION
**Pull request by lzaoral**
* enable smatch in fixtures
* update fixtures to only include publicly available products and mock configs

### CODE REVIEW

**Review by kdudka — APPROVED** [review]
This works for me but let's double check whether all the changes are compatible with the public OSH deployment that @siteshwar is working on.

**Comment by lzaoral** [comment]
@kdudka Definitely!  In the meantime, I might as well add the fixtures for the suggested checker groups in #111.

**Comment by lzaoral** [comment]
Hmm, the `multi` profile fixture should be updates as well to include `valgrind` and `smatch` and `gcc-unstable` should be removed as that seems to be just a remnant of some experiment.

**Comment by lzaoral** [comment]
... and there is no profile for `pylint` now.

**Review by siteshwar — APPROVED** [review]

**Review by kdudka — APPROVED** [review]

**Pull request merged**
