### PR TITLE
hub: rewrite generation and registration of `ModelAdmin` classes

### PR DESCRIPTION
**Pull request by lzaoral**
The original code was rather complicated and undocumented.  The new one retains a lot of its functionality (mainly creation of links for Relationship fields) while documenting the code and addition useful features like automatic population of `search_fields`, `autocomplete_fields`, `filter_horizontal` and `list_filter`.

Also, the `LogEntryAdmin` view is now read-only.

Resolves: https://github.com/openscanhub/openscanhub/issues/132

### CODE REVIEW

**Comment by lzaoral** [comment]
@kdudka Feel free to add additional reviewers.

**Comment by kdudka** [comment]
Thank you for working on it!  The updated admin interface looks good.  Two questions:
- Would it be possible to reintroduce the `Binding` column at `/admin/scan/scan/`?
- Do the changes conflict with #108?  Would it make sense to merge #108 first?

**Comment by lzaoral** [comment]
> https://github.com/release-engineering/kobo/blob/9af65943b183e2904b47855cbc820b8dda2d5643/kobo/hub/models.py#L561

> Do the changes conflict with https://github.com/openscanhub/openscanhub/pull/108? Would it make sense to merge https://github.com/openscanhub/openscanhub/pull/108 first?

Yes and yes.  If those tests test what they claim to test, they should show unintended changes in the admin views.

**Review by kdudka — APPROVED** [review]
This brings a major user experience improvement for OSH admins!  And without any unwanted side effects as far as I can see...

**Comment by lzaoral** [comment]
The TODO entries from previous comment are not important according to @kdudka.  Therefore, I'll squash the fixups and this PR is ready to be merged.

**Pull request merged**
